language: bash
services: docker

env:
  - VERSION=12
  - VERSION=12 FORCE_DEB_BUILD=1
  - VERSION=12 VARIANT=alpine
  - VERSION=11
  - VERSION=11 FORCE_DEB_BUILD=1
  - VERSION=11 VARIANT=alpine
  - VERSION=10
  - VERSION=10 FORCE_DEB_BUILD=1
  - VERSION=10 VARIANT=alpine
  - VERSION=9.6
  - VERSION=9.6 FORCE_DEB_BUILD=1
  - VERSION=9.6 VARIANT=alpine
  - VERSION=9.5
  - VERSION=9.5 FORCE_DEB_BUILD=1
  - VERSION=9.5 VARIANT=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VERSION/$VARIANT"
  - image="postgres:${VERSION}${VARIANT:+-${VARIANT}}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      if [ -n "${FORCE_DEB_BUILD:+x}" ]; then
        [ "$(dpkg --print-architecture)" = 'amd64' ]
        grep -qE 'amd64[|]' Dockerfile
        sed -ri -e 's/amd64[|]//g' Dockerfile
        ! grep -qE 'amd64[|]' Dockerfile
      fi
      docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
