language: bash
services: docker

env:
  - VERSION=9.6
  - VERSION=9.6 VARIANT=alpine
  - VERSION=9.5
  - VERSION=9.5 VARIANT=alpine
  - VERSION=9.4
  - VERSION=9.4 VARIANT=alpine
  - VERSION=9.3
  - VERSION=9.3 VARIANT=alpine
  - VERSION=9.2
  - VERSION=9.2 VARIANT=alpine
  - VERSION=10
  - VERSION=10 VARIANT=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - image="postgres:${VERSION}${VARIANT:+-${VARIANT}}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
